name: korean_history_bite
description: Boost Your Korean History IQ
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State Management
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

  # Local Database
  drift: ^2.30.0
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  path: ^1.9.1

  # Firebase
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6
  firebase_remote_config: ^6.1.3

  # Monetization
  google_mobile_ads: ^7.0.0
  in_app_purchase: ^3.2.3

  # UI
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

  # Utilities
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.4
  in_app_review: ^2.0.11
  upgrader: ^12.3.0
  url_launcher: ^6.3.2
  app_tracking_transparency: ^2.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.30.0
  build_runner: ^2.10.4
  riverpod_generator: ^4.0.0+1
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/data/
    - assets/data/questions/
    - assets/images/
